"""
End-to-end demonstration test against the synthetic 30-query gold-set
fixture referenced in the v0.8 governance PR description
(tests/fixtures/g3_demo/, generated by scripts/build_g3_demo.py).

Uses the real sentence-transformers DeterministicEmbedder (no GGUF/llama.cpp
required) to embed queries — this is a real, non-mocked retrieval run against
a real v1.3 pack, not a stubbed geometry test like test_g3_gate.py.

Runs against a scratch copy of the fixture so the checked-in pack (which
noema-gate stamp mutates in place) is never modified by the test suite.
"""

import os
import shutil
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

import pytest

from embedder.deterministic_embedder import DeterministicEmbedder
from noema_gate import run_gate, stamp_gate, verify_gate

_FIXTURE_ROOT = os.path.join(os.path.dirname(__file__), "..", "fixtures", "g3_demo")


@pytest.fixture
def demo_pack_dir(tmp_path):
    src = os.path.join(_FIXTURE_ROOT, "pack")
    dst = tmp_path / "pack"
    shutil.copytree(src, dst)
    return dst


def test_demo_fixture_run_stamp_verify(demo_pack_dir):
    goldset_path = os.path.join(_FIXTURE_ROOT, "goldset.jsonl")
    policy_path = os.path.join(_FIXTURE_ROOT, "policy.yaml")

    embedder = DeterministicEmbedder()

    def embed_query(q):
        return embedder.embed_texts([q])[0]

    result = run_gate(
        pack_dir=demo_pack_dir,
        goldset_path=goldset_path,
        policy_path=policy_path,
        embed_query_fn=embed_query,
        embedder_id=embedder.metadata.embedding_model,
    )

    assert len(result.report.per_query) == 30
    assert result.dangling == {}
    assert result.report.recall_at_k >= result.report.threshold  # demo policy calibrated to pass

    stamp_result = stamp_gate(demo_pack_dir, result.report_path, approved_by="taka")
    assert stamp_result.manifest["governance"]["promotion"]["status"] == "promoted"

    verify_result = verify_gate(demo_pack_dir)
    assert verify_result.ok, verify_result.reasons
