# GitHub Actions: Notify Discord on GitHub Releases
# Place this file at .github/workflows/discord-release.yml
# Requirements:
#   - Create a GitHub Actions secret named DISCORD_WEBHOOK_URL containing your Discord channel webhook URL
# Behavior:
#   - Triggers on published and prereleased GitHub Releases
#   - Sends an embedded message to Discord with tag/name, link, author, and a trimmed body

name: Notify Discord on Release

on:
  release:
    types: [published, prereleased]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Release to Discord
        uses: actions/github-script@v7
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          script: |
            const { release, repository } = context.payload;
            if (!release) {
              core.setFailed("No release payload found.");
              return;
            }

            const owner = repository?.owner?.login || context.repo.owner;
            const repo = repository?.name || context.repo.repo;
            const title = `New release in ${owner}/${repo}: ${release.name || release.tag_name}`;
            const body = (release.body && release.body.length > 0) ? release.body : `Tag: ${release.tag_name}`;

            const payload = {
              embeds: [{
                title,
                url: release.html_url,
                description: body.substring(0, 900),
                color: 0xFFD700,
                footer: { text: release.author?.login ? `by ${release.author.login}` : "" }
              }]
            };

            const res = await fetch(process.env.DISCORD_WEBHOOK_URL, {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify(payload)
            });

            if (!res.ok) {
              const text = await res.text();
              core.setFailed(`Discord webhook failed: ${res.status} ${res.statusText} - ${text}`);
            } else {
              core.info(`Sent release ${release.tag_name} to Discord`);
            }

